spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDBMS_URL}
    username: ${RDBMS_USERNAME}
    password: ${RDBMS_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100
      open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: false
    locations: classpath:db/migration, classpath:db/seed
  elasticsearch:
    uris: ${ELASTIC_SEARCH_URL}
    username: ${ELASTIC_SEARCH_USERNAME}
    password: ${ELASTIC_SEARCH_PASSWORD}

decorator:
  datasource:
    p6spy:
      enable-logging: false
      logging: slf4j
      multiline: true

s3:
  bucket: baekgwa-blog-s3-bucket
  region: ap-northeast-2
  accessKey: ${S3_ACCESS_KEY}
  secretKey: ${S3_SECRET_KEY}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}

elasticsearch:
  url: ${ELASTIC_SEARCH_URL}
  username: ${ELASTIC_SEARCH_USERNAME}
  password: ${ELASTIC_SEARCH_PASSWORD}
  embeddingIndexName: ${ELASTIC_SEARCH_EMBEDDING_INDEX}

logstash:
  url: ${LOGSTASH_URL}